---
title: "R Notebook"
output: html_notebook
authors: "Andrew Rost & Pavel Sachivichik"
purpose: "Financial Analysis of Oil Companies"
date: "12/5/2019"
---



```{r message=FALSE, warning=FALSE}
library(readr)
library(DataComputing)
library(dplyr)
library(tidyverse)
library(lubridate)
library(readr)
library(ggplot2)




CVX <- read_csv("CVX.csv")
head(CVX)

HAL <- read_csv("HAL.csv")
head(HAL)

XOM <- read_csv("XOM.csv")
head(XOM)

SP <- read_csv("GSPC.csv")

BrentOilPrices <- read_csv("BrentOilPrices.csv")
BrentOilPrices <-
  BrentOilPrices %>%
  mutate(Date = mdy(Date))
```

```{r}
adjustS <- 2790.37/120.67
adjustH <- 32.66/120.67
combined <-
CVX %>%
inner_join(HAL, by=c("Date"="Date")) %>%
inner_join(SP, by=c("Date"="Date")) %>%
filter(Date>="2018-12-01") %>%
mutate(CVX = Close.x) %>%
mutate(SP= Close/adjustS) %>%
mutate(HAL = Close.y/adjustH) %>%
select(Date, CVX, SP, HAL)
tail(combined)
g <- ggplot(data = combined) + geom_line(aes(x = Date, y=CVX, color = "CVX")) +
geom_line( aes(x=Date, y = combined$SP,color = "SP")) +
geom_line(aes(x=Date, y = combined$HAL,color = "HAL")) + ylab("Closing Price") + scale_colour_manual(name='', values=c('SP'= "red",
'HAL'='blue', "CVX"="black"))
g
```
```{r}
adjustO <- 60.17/32.66
combined2 <-
HAL %>%
inner_join(BrentOilPrices, by=c("Date"="Date")) %>%
filter(Date>="2018-12-01") %>%
mutate(HAL = Close) %>%
mutate(Oil= Price/adjustO) %>%
select(Date, HAL, Oil)
g <- ggplot(data = combined2) + geom_line(aes(x = Date, y = HAL, color = "HAL")) +
geom_line(aes(x=Date, y = Oil, color = "Oil")) + ylab("Price") + scale_colour_manual(name='', values=c('Oil'= "red", "HAL"="black"))
g
```

```{r}
adjustO <- 60.17/120.67
combined3 <-
CVX %>%
inner_join(BrentOilPrices, by=c("Date"="Date")) %>%
filter(Date>="2018-12-01") %>%
mutate(CVX = Close) %>%
mutate(Oil= Price/adjustO) %>%
select(Date, CVX, Oil)
g <- ggplot(data = combined3) + geom_line(aes(x = Date, y = CVX, color = "CVX")) +
geom_line(aes(x=Date, y = Oil, color = "Oil")) + ylab("Price") + scale_colour_manual(name='', values=c('Oil'= "red", "CVX"="black"))
g
```

```{r}
adjustO <- 60.17/81.22
combined4 <-
XOM %>%
inner_join(BrentOilPrices, by=c("Date"="Date")) %>%
filter(Date>="2018-12-01") %>%
mutate(XOM = Close) %>%
mutate(Oil= Price/adjustO) %>%
select(Date, XOM, Oil)
g <- ggplot(data = combined4) + geom_line(aes(x = Date, y = XOM, color = "XOM")) +
geom_line(aes(x=Date, y = Oil, color = "Oil")) + ylab("Price") + scale_colour_manual(name='', values=c('Oil'= "red", "XOM"="black"))
g
```
```{r}
CombinedData <-
  
barGraphHelper(XOM)
```


